services:
  nacos:
    platform: linux/amd64
    image: nacos/nacos-server:v2.3.2
    container_name: nacos
    environment:
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
    ports:
      - "8848:8848"
      - "9848:9848"
    volumes:
      - nacos_data:/home/nacos/data

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123456
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  postgresql:
    image: postgres:15
    platform: linux/amd64
    container_name: postgresql
    environment:
      POSTGRES_USER: msp
      POSTGRES_PASSWORD: msp123
      POSTGRES_DB: msp_requirement
      TZ: Asia/Shanghai
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  requirement:
    build: .
    container_name: requirement
    ports:
      - "8080:8080"
    environment:
      - NACOS_ADDR=nacos:8848
      - NACOS_NAMESPACE=
    depends_on:
      - nacos
      - postgresql

volumes:
  nacos_data:
  minio_data:
  pg_data:
